### ISSUE TITLE
EEPROM Page Size and Number of Pages

### ISSUE THREAD

**Issue by pkr97** [STMicroelectronics/STM32CubeF3#16]
Trying to use the example provided for EEPROM interfacing with STM32. The module I'm trying to use is AD7147. How can I get the number of PAGES and PAGE size? It is not given. ..

Best,
Prasanna

**Comment by RKOUSTM** [comment]
Hi @pkr97,

The point you reported is not directly related to the firmware published in this repository and is out of the scope of STMicroelectronics' activity. They are rather treated at [ST Community](https://community.st.com/s/topic/0TO0X000000BSqSWAW/stm32-mcus) level. Please allow me to redirect you to address your request in [this](https://community.st.com/s/question/0D53W00000yZ36y/how-to-implement-i2c-communication-with-a-sensor-like-ad71471) discussion section where the same issue is addressed.

To more investigate this issue and speed up the analysis procedure, could you please give more details about your application and the stm32F3 board is a custom board or not.  Also, please detail more the relationship between the CapTouch™ Programmable Controller for Single-Electrode Capacitance Sensors AD7147 and your developed example.

Now, as this issue is not directly related to some software component published within this repository (CMSIS, HAL, BSP, etc.) but rather to a user application, please allow me to close it.

Thank you for your comprehension. We are looking forward to reading from you again.

With regards,
